### ISSUE TITLE
[Feature] Handle system packages for Mac OS X

### ISSUE THREAD

**Issue by arjunsuresh** [octoml/cm-mlops#7]
Currently the system utils ic is handling Ubuntu and Windows packages only. We need to extend this to Mac OS X and non-debian linux flavours too.

https://github.com/octoml/cm-mlops/blob/main/ic/prototype-get-sys-utils-cm/customize.py

**Comment by gfursin** [comment]
Hi Arjun,

We get the basic host OS info using Python whenever we start running any IC. We get this info here: https://github.com/mlcommons/ck/blob/master/ck2-repo-mlops/automation/utils/module.py#L55
```bash
cm get_host_os_info utils
```

This is not a very sophisticated method and it's just used to understand if IC is run on Windows (to use .bat files) or on any sort of Linux (to use .sh files). 

I believe that we should add more sophisticated methods to detect OS in the IC "detect-os": https://github.com/octoml/cm-mlops/tree/main/ic/prototype-detect-os 

So if a new IC relies on extended OS info (not just Windows or Linux but MacOS vs Debian OS), we need to add a dependency on detect-os which will return extra env related to the OS FLAVOR and related tools (apt yum; lscpu ...) ... What do you think?

**Comment by gfursin** [comment]
I believe it's done now!
